---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	generate_question(generate_question)
	generate_followup_question(generate_followup_question)
	validate_question(validate_question)
	score_answer(score_answer)
	retrieve_related_questions(retrieve_related_questions)
	adapt_difficulty(adapt_difficulty)
	__end__([<p>__end__</p>]):::last
	__start__ -.-> generate_question;
	__start__ -.-> score_answer;
	adapt_difficulty -.-> generate_followup_question;
	adapt_difficulty -.-> generate_question;
	generate_followup_question --> validate_question;
	generate_question --> validate_question;
	retrieve_related_questions --> adapt_difficulty;
	score_answer --> retrieve_related_questions;
	validate_question -.-> __end__;
	validate_question -.-> generate_question;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
